# -*- mode: python ; coding: utf-8 -*-
# PyInstaller spec — Eastern Studios Image Studio
# Build: pyinstaller es_image_studio.spec

from PyInstaller.utils.hooks import collect_all, collect_submodules

datas_rembg,   binaries_rembg,   hiddenimports_rembg   = collect_all("rembg")
datas_onnx,    binaries_onnx,    hiddenimports_onnx    = collect_all("onnxruntime")
datas_webview, binaries_webview, hiddenimports_webview = collect_all("webview")

a = Analysis(
    ["desktop.py"],
    pathex=["."],
    binaries=binaries_rembg + binaries_onnx + binaries_webview,
    datas=datas_rembg + datas_onnx + datas_webview + [
        ("app.py", "."),
    ],
    hiddenimports=(
        hiddenimports_rembg
        + hiddenimports_onnx
        + hiddenimports_webview
        + collect_submodules("uvicorn")
        + collect_submodules("fastapi")
        + collect_submodules("PIL")
        + collect_submodules("starlette")
        + ["anyio", "anyio._backends._asyncio", "h11",
           "httptools", "python_multipart"]
    ),
    hookspath=[],
    runtime_hooks=[],
    excludes=["tkinter", "matplotlib", "scipy", "pandas"],
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="ES Image Studios",
    debug=False,
    strip=False,
    upx=True,
    console=False,
    icon="icon.ico",    # generated by build.bat — replace with your own
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name="ES Image Studios",
)
